### ISSUE TITLE
Auto Mini-game, Additional trigger

### ISSUE THREAD

**Issue by NajmAjmal** [alexlostorto/magic-notes#10]
Hi,

In version [3.0.5](https://github.com/alexlostorto/magic-notes/releases/tag/v3.0.5), You added these 2 new features.

- Automatically select the next task when pressing Enter in homework.
- Automatically select the 'auto higher or lower' mini-game when pressing Enter, the mini-game section.

I was wondering as well, as pressing “Enter” could add clicking the “Continue” Button on sparxmaths, which can also trigger events aforementioned above.

Also, if this feature gets implemented, could you share the code snippet with me

Thanks Najm,

**Comment by alexlostorto** [comment]
Are you suggesting to create an additional button that would pop-up on those pages?

If so, then I think that would be unnecessarily complex (due to the different screen sizes and positioning of the button) and possibly make the screen more cramped. If the user wants to continue, they can just click the next task or the minigame of their choice.

I think of the 'Enter' feature as a hotkey which the user can use if they really wish, but if they don't want to then it will be like it was never there. The 'Continue' button you are suggesting would probably be a new feature that would be forced on users who may not want it there.

I hope I answered your question, open this issue again if I didn't!

Thank you for the suggestion and good luck with implementing it in your version.

---

_PS: At least for the foreseeable future I won't be pursuing any enhancements or fixes to Magic Notes. I am currently doing my GCSE's and don't want to get too distracted :)_

**Comment by NajmAjmal** [comment]
Hi,

I am not suggesting adding a button, but utilising the current button that Sparxmaths currently offers. When a section of work is completed, there is a button called “Continue”. I was Suggesting that we add a trigger to this button, so it acts like pressing “Enter”.

But i see your point on "**would probably be a new feature that would be forced on users who may not want it there.**". and maybe if the popup.html was added, there could be a toggle button which could enable extra features such as this.

Thanks for listening to my Suggestions, Najm.

**Comment by alexlostorto** [comment]
Yeah, that definitely sounds pretty interesting!

If I have more time in the future then maybe I will implement a settings popup that can be toggled. Sadly I can't really pursue any enhancements at the moment, but if you have any implementations, feel free to send the code over :)
