### ISSUE TITLE
Confusion on privacy policy

### ISSUE THREAD

**Issue by hosm1002** [alexlostorto/magic-notes#8]
I am quite confused on this one part of the privacy policy: 
![image](https://user-images.githubusercontent.com/131755538/236154740-fa55554f-af90-46b9-9d54-f45b58f1164c.png)
Why does it need to store/send my login info. I might be interpreting it wrong.

**Comment by hosm1002** [comment]
This is from a different version but i realised that this was the original.

**Comment by alexlostorto** [comment]
_Before I begin... I do not hold any power or responsibility over what other people do with this program. If you use someone else's version of my program, then you are accepting that they may be taking your data or distributing malicious code._

---

Hi, thanks for creating this issue, privacy is something we hold in high regard so I appreciate your concern.

### Data Collected

Below is the list of data we collect:
- Account creation dates
- Time of logins
- MD5 encryptions of usernames
- Answer data

### Why?

Account creation dates and login times are collected to estimate the extension's growth and activity. I was also going to add a daily or weekly streak to the extension, so the login data would be used for that - keeping track of how often students complete their homework might encourage students to return and keep using SparxMaths.

Usernames are encrypted and used to associate each user's data with their account (otherwise all the data would be mixed up).

Answer data is collected to help improve the reliability of the answer detection algorithm.

---

_If you have any more questions regarding privacy, feel free to open this issue again or don't use the extension._

**Comment by hosm1002** [comment]
I did end up using your version
